create database CSE_3B_348;

USE CSE_3B_348;

create table bSTUDENT
(ROLLNO INT,
NAME VARCHAR(50)
);
INSERT INTO bSTUDENT(ROLLNO,NAME) VALUES(101,'JEEL'),(102,'JENIL'),(103,'BRIND'),(105,null);

SELECT * FROM bSTUDENT;

SELECT NAME FROM bSTUDENT;
SELECT ROLLNO FROM bSTUDENT;

SELECT * FROM bSTUDENT WHERE ROLLNO>101
SELECT * FROM bSTUDENT WHERE NAME='JEEL'

SELECT * FROM bSTUDENT WHERE NAME IS NULL
