create database CSE_3B_348;

USE CSE_3B_348;

create table bSTUDENT(ROLLNO INT,NAME VARCHAR(50));

INSERT INTO bSTUDENT(ROLLNO,NAME) VALUES(101,'JEEL'),(102,'JENIL'),(103,'BRIND'),(105,null);

SELECT * FROM bSTUDENT;

SELECT NAME FROM bSTUDENT;
SELECT ROLLNO FROM bSTUDENT;

SELECT * FROM bSTUDENT WHERE ROLLNO>101
SELECT * FROM bSTUDENT WHERE NAME='JEEL'

SELECT * FROM bSTUDENT WHERE NAME IS NULL

SELECT TOP 2 * FROM bSTUDENT

SELECT TOP 10 PERCENT * FROM bSTUDENT

SELECT DISTINCT NAME FROM bSTUDENT

--AND
SELECT * FROM bSTUDENT WHERE ROLLNO=103 AND NAME='BRIND'

--OR
SELECT * FROM bSTUDENT WHERE ROLLNO=103 OR ROLLNO=101

--IN
SELECT * FROM bSTUDENT WHERE ROLLNO IN (101,102,103)

SELECT * FROM bSTUDENT WHERE NAME IN('JEEL','JENIL')

--NOT
SELECT * FROM bSTUDENT WHERE NOT NAME='JENIL'

SELECT * FROM bSTUDENT WHERE NAME<>'BRIND'

SELECT * FROM bSTUDENT WHERE NAME!='JEEL'

--BETWEEN
SELECT * FROM bSTUDENT WHERE ROLLNO BETWEEN 101 AND 103

SELECT * FROM bSTUDENT
SELECT * FROM cSTUDENT

--into
SELECT * INTO cSTUDENT FROM bSTUDENT

--False Condition
SELECT NAME,ROLLNO INTO dSTUDENT
FROM bSTUDENT WHERE 1=0 

--INSERE WHERE NAME = JEEL
INSERT INTO eSTUDENT

--DELETE
DELETE FROM bSTUDENT WHERE NAME IS NULL
SELECT * FROM bSTUDENT

--UPDATE
UPDATE bSTUDENT SET NAME = 'NULL' WHERE ROLLNO = 101






--IT IS USE TO ADD NEW COLUMN
--IT ID USE TO DROP THE COLUMN




